indiah444/Media-Polarisation-Project

- .github/workflows/article_combiner_quality.yml
- .github/workflows/dashboard_quality.yml
- .github/workflows/database_quality.yml
- .github/workflows/democracy_now_scraper_quality.yml
- .github/workflows/email_generator_quality.yml
- .github/workflows/fox_news_scraper_quality.yml
- .github/workflows/news_sentiment_analyser_quality.yml
- article_combiner/test_dummy.py
- dashboard/test_dummy.py
- database/test_dummy.py
- democracy_now_scraper/test_dummy.py
- email_generator/test_dummy.py
- fox_news_scraper/test_dummy.py
- news_sentiment_analyser/test_dummy.py
These are template workflows for each folder that will contain python files. I have also inserted dummy testing files to prevent pytest error. These must be deleted when real tests are created.
The workflows are mostly copies of each other and can be edited per the needs of the corresponding folder.
> create workflows for testing and linting

- database/schema.sql
- Created schema SQL file for database, creating the tables and relationships between them, columns and their data types, constraints etc.
- Could someone check over this file to make sure the constraints are all correct?
> Schema SQL file for database.

- database/connect.sh
- Created shell script for connecting to the database.
- This automates the connection process, saving time and cutting out human error.
> Shell script for connecting to database.

- database/schema.sql
- Updated tables and seed data in `schema.sql` in line with changes in ERD and suggestions made by coaches.
> Updated schema in line with changes to ERD.

- database/generate_dummy_data.py
Now consistent with the new Schema, and doesn't attempt to insert IDs.
> Fixed dummy data generation

- database/README.md
- database/generate_dummy_data.py
- Added some description of the RDS
- Added description/how-to for fake data generation and running locally
> Updated README.md to reflect recent changes in database folder

- news_sentiment_analyser/extract_s3.py
- news_sentiment_analyser/requirements.txt
solves #42 
Extracts from s3, returns as a dataframe and then deletes file from s3.
> Extract from s3

- database/README.md
- database/generate_dummy_data.py
- database/test_dummy.py
- updated the commits from the last "update readme" pull request (had an issue with pushing)
> Refactoring fake data files

- news_sentiment_analyser/extract_s3.py
Added another check that csv uploaded ends with "_article_data.csv"
Also removed whitespaces.
> checks csvs end with _article_data.csv

- news_sentiment_analyser/extract_s3.py
- news_sentiment_analyser/requirements.txt
- news_sentiment_analyser/test_extract_s3.py
Added unit tests for extraction for s3 functionality.
> Testing s3 extraction

- fox_news_scraper/extract_fn.py
- Refactored function to avoid repeated code.
> Refactoring functions in extract_fn.py

- fox_news_scraper/conftest.py
- fox_news_scraper/requirements.txt
- fox_news_scraper/test_extract_fn.py
- Very basic initial tests for `extract_fn.py` (more will have to be added later, along with a coverage report).
- Conftest file created for storing pytest fixtures.
- Requirements file updated to include necessary libraries.
> Initial tests for extract script

- news_sentiment_analyser/openai_topics.py
- news_sentiment_analyser/test_database_functions.py
- news_sentiment_analyser/test_openai_topics.py
solves #70 
Unit tests for openi_topics.py and database_functions.py.
> Testing openai

- news_sentiment_analyser/requirements.txt
- news_sentiment_analyser/sentiment_analysis.py
- news_sentiment_analyser/test_sentiment_analysis.py
- Performs sentiment analysis on a text column in a dataframe
- assumes cleaned data
- also includes a method to aggregate by source,topic grouping 
- unit tests included
> Wrote script to perform Sentiment analysis on a column

- fox_news_scraper/load_csv_fn.py
- fox_news_scraper/requirements.txt
- `load_csv_fn.py` file transforms the article data into a CSV and loads it into the S3 bucket.
- Updated requirements file with necessary libraries.
> Load script for Fox News article data.

- fox_news_scraper/pipeline_fn.py
- fox_news_scraper/requirements.txt
- Created `pipeline_fn.py` that utilises functions defined with other scripts to combine the entire pipeline structure.
- Includes a lambda handler function so the script can later be dockerised and deployed on an AWS Lambda.
> Main pipeline script for Fox News Scraper.

- fox_news_scraper/README.md
- fox_news_scraper/pipeline_fn.py
- Updated `README` in `fox_news_scraper` folder.
- Import names in `pipeline_fn.py` corrected.
> Updated README for Fox News scraper.

- news_sentiment_analyser/database_functions.py
- news_sentiment_analyser/load_rds.py
- news_sentiment_analyser/test_database_functions.py
- news_sentiment_analyser/test_load_rds.py
solves #12 #14 
Bulk insertion into articles and article_topic_assignment table.
> Load to rds

- fox_news_scraper/clean_fn.py
- fox_news_scraper/test_clean_fn.py
Wrote tests for clean_fn and refactored a bit (to make writing tests easier) but core functionality is the same except that punctuation is no longer filtered out (as this affects sentiment analysis scores). Coverage now at 79%.
> Writing tests for clean_fn

- database/schema.sql
- Added new columns to `article` table for the title and content polarity score.
- Added a composite unique constraint to the `article_topic_assignment` table.
- Added missing comma to `article` table to get rid of error.
> Updating schema SQL file.

- database/README.md
- Updated `README` in the `database` folder to include justification of the `source_political_leaning` attribute in the `source` table.
- Relevant further reading links also supplied in README.
> Updated README to include justification of political leaning attribute.

- fox_news_scraper/README.md
- Updated `README` in `foxs_news_scraper` folder with information on dockerising `pipeline_fn.py`
> Updated README with information about Dockerfile.

- fox_news_scraper/Dockerfile
- fox_news_scraper/pipeline_fn.py
- fox_news_scraper/requirements.txt
- Dockerfile for `pipeline_fn.py` with all necessary files copied over.
- Order of libraries changed in `requirements.txt` to fix bug related to `grequests`.
- Small typo in `pipeline_fn.py` fixed in success message.
> Dockerfile for Fox News pipeline

- .github/ISSUE_TEMPLATE/user-story-issue-template.md
Just added a template to make it easier to write issues quickly
> Update issue templates

- news_sentiment_analyser/database_functions.py
- news_sentiment_analyser/load_rds.py
- news_sentiment_analyser/openai_topics.py
- news_sentiment_analyser/pipeline_analysis.py
- news_sentiment_analyser/sentiment_analysis.py
- news_sentiment_analyser/test_database_functions.py
- news_sentiment_analyser/test_load_rds.py
- news_sentiment_analyser/transform_articles.py
Transforms articles by, removing duplicates, adding polarity, adding topics and removing punctuation.
> Transform articles

- database/schema.sql
- fox_news_scraper/test_pipeline_fn.py
- Adding new topic to `schema.sql` to reflect popular current news issues.
> Adding new topic to static data.

- news_sentiment_analyser/openai_topics.py
- news_sentiment_analyser/transform_articles.py
> refactoring and allowing punctuation

- dashboard/db_functions.py
- dashboard/requirements.txt
some basic functions to get started
> batabase functions

- news_sentiment_analyser/Dockerfile
- news_sentiment_analyser/requirements.txt
Dockerised pipeline into a Dockerfile.
> Dockerise pipeline

- fox_news_scraper/Dockerfile
- fox_news_scraper/clean_fn.py
- fox_news_scraper/load_csv_fn.py
- fox_news_scraper/test_clean_fn.py
- Updated `clean_fn.py` file to refactor functions.
- Updated `test_clean_fn.py` in line with refactored functions.
- Removed `clean_fn.py` from Dockerfile to fix bug in AWS Lambda to do with `nltk`.
> Updated cleaning process for Fox News scraper.

- fox_news_scraper/README.md
- fox_news_scraper/test_load_csv_fn.py
- Unit tests for `load_csv_fn` added
> Some leftover load csv fn unit tests 

- dashboard/requirements.txt
- dashboard/word_cloud_dashboard.py
- Created word clouds based on how frequently words appear in article content by source.
- These are initial visualisations and things like colour, position, extra data cleaning, filtering etc. can be changed at a later stage.
> Word cloud visualisations for article content.

- daily-emailing/Dockerfile
- daily-emailing/daily_email.py
- weekly-emailing/Dockerfile
- weekly-emailing/weekly_email.py
> Dockerised emaiiling

- README.md
- Updated top-level `README.md` file with additional information.
- Please let me know if there's anything I missed or if anything needs to be rephrased!
> Updated top-level README with additional information on project.

- dashboard/Home.py
- dashboard/pages/Subscribe.py
- Updated `Home.py` to display more information on the project and how the dashboard works. 
- Open to feedback, can be cut down or expanded if needs be.
- I will also look into more styling for the dashboard, so homepage subject to change.
> Updated homepage for dashboard.

- daily-emailing/README.md
- weekly-emailing/README.md
Readmes for both daily and weekly email generation.
Includes overview, prerequisites (will need to check over), folder structure, set up and running locally, and deployment.
> Readmes for emailing scripts

- news_sentiment_analyser/README.md
- updated the ETL pipeline with setup instructions, overview, and some details on implementation
> Update ETL pipeline readme 

- dashboard/pages/Word_Clouds.py
- dashboard/pages/word_cloud_dashboard.py
- Renamed file to `Word_Clouds.py` to standardise names of pages on dashboard.
- Added cacheing to NLTK downloads to fix broken pipe bug.
- Updated colour scheme on word clouds to make them more distinctive.
> Changes to word clouds

- weekly-emailing/graphs.py
- weekly-emailing/weekly_email.py
Edited the weekly email pdf to have colours in the graphs and a correct bar chart.
> added colours to pdf graphs and fixed bar-chart

- dashboard/d_graphs.py
- news_sentiment_analyser/database_functions.py
- news_sentiment_analyser/test_database_functions.py
- news_sentiment_analyser/test_load_rds.py
- news_sentiment_analyser/test_openai_topics.py
- news_sentiment_analyser/test_transform_articles.py
- news_sentiment_analyser/transform_articles.py
> Testing transform

- dashboard/test_db_functions.py
> unit tests for dashboard db functions

- dashboard/d_graphs.py
- dashboard/pages/Sentiment_Over_Time.py
- added heatmaps
- made changes to account for empty data/one source only cases so that they no longer raise an error
- Changed the structure of the page
> Update time change dashboard page

- .github/workflows/daily_email_generator_quality copy.yml
- .github/workflows/dashboard_quality.yml
- daily-emailing/d_db_funcs.py
- daily-emailing/daily_email.py
- daily-emailing/html_content.py
- daily-emailing/test_d_db_funcs.py
- daily-emailing/test_daily_email.py
- daily-emailing/test_dummy.py
- daily-emailing/test_html_content.py
- news_sentiment_analyser/README.md
- terraform/main.tf
- terraform/variables.tf
- weekly-emailing/conftest.py
- weekly-emailing/graphs.py
- weekly-emailing/pdf_content.py
- weekly-emailing/requirements.txt
- weekly-emailing/test_dummy.py
- weekly-emailing/test_graphs.py
- weekly-emailing/test_pdf_content.py
- weekly-emailing/test_w_db_funcs.py
- weekly-emailing/test_weekly_email.py
- weekly-emailing/w_db_funcs.py
- weekly-emailing/weekly_email.py
Added test cases to the daily-emailing and weekly-emailing folders.
Also refactored/created new functions to make the testing easier 
and the adjusted the scripts themselves more consistent.
> Email test cases

- dashboard/pages/5_Word_Clouds.py
- Updating custom stopwords in `5_Word_Clouds.py`
> Fixing wordcloud

- dashboard/pages/3_Sentiment_Over_Time.py
- Adding colour to the "Sentiment Over Time" page.
- Changed names of variables to improve pylint score.
> Dashboard fixes - colour

- daily-emailing/README.md
- dashboard/README.md
- dashboard/d_graphs.py
- dashboard/upload_dashboard.sh
- database/README.md
- democracy_now_scraper/README.md
- fox_news_scraper/README.md
- news_sentiment_analyser/README.md
- terraform/README.md
- weekly-emailing/README.md
Went through and standardised formatting as well as removing any redundant/duplicate information.
Also fixed dashboard bug caused by string being split over two lines.
> Check readmes

- news_sentiment_analyser/README.md
- news_sentiment_analyser/clean_content.py
- news_sentiment_analyser/sentiment_analysis.py
- news_sentiment_analyser/test_clean_content.py
- news_sentiment_analyser/test_sentiment_analysis.py
- news_sentiment_analyser/transform_articles.py
- added custom stopwords and extra cleaning to sentiment analysis
- Included tests for new function
> added custom stopwords and extra cleaning to sentiment analysis

- dashboard/d_graphs.py
- dashboard/pages/3_Sentiment_Over_Time.py
- dashboard/pages/5_Word_Clouds.py
Added caching to everything that doesnt cause an error in streamlit.
Also added red/blue colours to time graph
> all cached up

- dashboard/1_Home.py
- Changed colours of fonts on main dashboard homepage to make it easier to read in dark mode.
- Added links to redirect users to different pages in the dashboard.
> Updating dashboard homepage - colours and links

- dashboard/pages/3_Sentiment_Over_Time.py
New visualisation (not taking into account recent colour scheme changes)
> Fixing heatmap weekday order and split into weeks

- dashboard/pages/5_Word_Clouds.py
- Added a function to lemmatise words in `5_Word_Clouds.py`
> Added lemmatization to word cloud

- dashboard/pages/5_Word_Clouds.py
- Added topic filtering to `5_Word_Clouds.py`
- Users can select multiple topics to be displayed in the word cloud.
- If no topics selected, word cloud will display keywords from all topics.
- Refactored repeated code into a function.
> Added topic filtering to word clouds.

- dashboard/d_graphs.py
- dashboard/pages/3_Sentiment_Over_Time.py
- dashboard/pages/5_Word_Clouds.py
- dashboard/upload_dashboard.sh
- terraform/README.md
- Fixed string bug causing the dashboard to crash
- Updated terraform readme to remind users to chmod 400 the .pem key
- Updated the dashboard/upload_dashboard.sh file to allow secret variable export without actually transferring the .env file
> fixed dashboard bug and updated readme

- dashboard/d_graphs.py
- dashboard/pages/3_Sentiment_Over_Time.py
- refactored sidebar into it's own function 
- cleaned up code 
- moved visualisation function into d_graphs
> Refactoring sentiment over time and fixing the granularity setting

- dashboard/pages/5_Word_Clouds.py
- Added more custom stop words
- Updated word cloud to make all words horizontal
- Word clouds now automatically show all keywords from last 7 days
> Updates to word clouds.

- dashboard/d_graphs.py
**changes made**
- All colour gradients are the same (range between -1 and 1, regardless of the min and max of the data)
- Minor formatting change
Closes isse #182
> Made colour gradients on heatmaps consistent

- dashboard/db_functions.py
- dashboard/pages/3_Sentiment_Over_Time.py
- refactored code to make testing easier now
> Refactored code on line graphs pages

- dashboard/pages/5_Word_Clouds.py
- Refactored `run_app` function as it was too long.
- Removed more stop words.
> Refactoring word clouds

- dashboard/dataframe_functions.py
- dashboard/db_functions.py
- dashboard/pages/3_Sentiment_Over_Time.py
- dashboard/pages/5_Word_Clouds.py
- dashboard/test_streamlit_pages.py
- added tests for streamlit pages using the streamlit module. Current code coverage is:
```
---------- coverage: platform darwin, python 3.12.6-final-0 ----------
Name                             Stmts   Miss  Cover
----------------------------------------------------
1_Home.py                           14      1    93%
d_graphs.py                         78     14    82%
dataframe_functions.py              18     12    33%
db_functions.py                     95      7    93%
pages/2_About.py                     5      0   100%
pages/3_Sentiment_Over_Time.py      72     45    38%
pages/4_Topic_Filter.py             24      2    92%
pages/6_Subscribe.py                35     15    57%
test_d_graphs.py                    67      1    99%
test_db_functions.py               116      0   100% …
```
> Clean files and test streamlit

- dashboard/pages/5_Word_Clouds.py
Fixed a small typo to reflect the refactored code. @indiah444 , I think this was my fault (came from a merge conflict somewhere)
> Fixed small typo

- dashboard/README.md
- fox_news_scraper/README.md
- Updated READMEs in both `fox_news_scraper` folder and the `dashboard` folder
> Updating READMEs

- dashboard/dataframe_functions.py
- dashboard/test_dataframe_functions.py
- unit tests added
- full coverage of dataframe_functions.py
> Added unit tests 

- dashboard/d_graphs.py
- dashboard/pages/3_Sentiment_Over_Time.py
- dashboard/pages/5_Word_Clouds.py
- dashboard/streamlit_components.py
- dashboard/test_streamlit_pages.py
- removed the double sidebar on the wordclouds page
- refactored streamlit components for easier testing 
- fixed the header format on the sentiment over time page
> Fixed dashboard formatting 

- dashboard/conftest.py
- dashboard/test_dataframe_functions.py
Addded two unit tests to dataframe_functions to cover the add_year_month_day_col method and give full coverage of the file.
> Addded two unit tests to dataframe_functions

- dashboard/pages/5_Word_Clouds.py
- Removed duplicated titles in `5_Word_Clouds.py`
> Removed unnecessary titles on word clouds.

- dashboard/1_Home.py
- dashboard/pages/3_Sentiment_Over_Time.py
- dashboard/pages/4_Topic_Filter.py
- dashboard/pages/5_Word_Clouds.py
- dashboard/pages/6_Subscribe.py
- Updated dashboard layout so the homepage layout is wide
- Page icon is now a newspaper emoji for every page (not just the homepage)
> Updated dashboard layout.

- README.md
- added a table of contents to the main readme file 
- fixed minor SPAG errors
> Add table of contents to the main README

- daily-emailing/README.md
- dashboard/d_graphs.py
- dashboard/dataframe_functions.py
- dashboard/pages/3_Sentiment_Over_Time.py
- dashboard/pages/5_Word_Clouds.py
- dashboard/test_dataframe_functions.py
- dashboard/test_streamlit_pages.py
- democracy_now_scraper/README.md
- fox_news_scraper/README.md
- news_sentiment_analyser/README.md
- news_sentiment_analyser/sentiment_analysis.py
- terraform/README.md
- terraform/main.tf
- terraform/variables.tf
- weekly-emailing/graphs.py
- weekly-emailing/pdf_content.py
Update some READMEs and increased pylint scores for certain files.
DO NOT MERGE YET. await confirmation.
> Readme double check

- dashboard/pages/3_Sentiment_Over_Time.py
- dashboard/pages/6_Subscribe.py
- dashboard/test_d_graphs.py
- dashboard/upload_dashboard.sh
- terraform/main.tf
- terraform/variables.tf
Democracy now typo is now fixed.
upload_dashboard.sh was missing a file now fixed
> Terraform fix

- fox_news_scraper/load_csv_fn.py
Fixed Fox news bug requiring grequests at the top of the file
> Please merge. Fix Fox news issue

- news_sentiment_analyser/README.md
- news_sentiment_analyser/extract_s3.py
- news_sentiment_analyser/test_extract_s3.py
Updated the news sentiment analyser readme.
> readme update
